### PR TITLE
Bump hedis

### PR DESCRIPTION
**Pull request by k-bx**
Useful for https://github.com/fpco/stackage/issues/1247

### CODE REVIEW

**Comment by k-bx** [comment]
@meteficha ping

**Comment by psibi** [comment]
@k-bx Can you update this PR since the latest hedis is 0.9.3 ?

**Comment by k-bx** [comment]
@psibi sure, done!

**Comment by psibi** [comment]
@snoyberg Can you merge this ? It seems I don't have the write access to this repo.

**Comment by snoyberg** [comment]
Done. @meteficha mind if I open up this repo to the standard Yesod contributor list?

**Pull request merged**
