### PR TITLE
updated: lts to 15

### PR DESCRIPTION
**Pull request by ncaq**
support new persinent and acid-state.

### CODE REVIEW

**Comment by ncaq** [comment]
@snoyberg notify.
I use Yesod version more than lts-15.
So I write stack.yaml

```yaml
extra-deps:
  - github: ncaq/serversession
    commit: fc77ca238ed055a2d81716cc533fbe266aa9ad54
    subdirs:
      - serversession-backend-persistent
      - serversession-frontend-yesod
```

Do you think to problem of PR?

**Comment by snoyberg** [comment]
I'm not sure what you're asking here. But I'm guessing this code is ready for a review/merge/release, is that what the question is?

**Comment by ncaq** [comment]
@snoyberg yes, I want to merge this pull request.
Because I modify serversession to compatible lts-15 acid state.

**Review by snoyberg — CHANGES_REQUESTED** [review]
LGTM. I can't say I'm an expert on the code here, but I'm OK with it. Can you add relevant version bumps and changelog entries? Also, just to confirm: do we need any tighter lower bounds on dependencies? It didn't look like it, but I wanted to confirm.

**Comment by ncaq** [comment]
@snoyberg 
> do we need any tighter lower bounds on dependencies?

Because base lib changed function argument signature.
If I support both version, CPP branch too much.

**Comment by snoyberg** [comment]
LGTM, thanks!

**Pull request merged**
