### PR TITLE
updated: LTS: 19

### PR DESCRIPTION
**Pull request by ncaq**
The work was done mainly to support the new version of persistent.
We have achieved some success, but there are a few things left to be done.

@snoyberg 
By the way, who is the maintainer of this project now?

## Things left undone

We were not able to maintain the `Example'.
For some reason, the new `mkServerSessionDefs` works in the test project.
I get a Kind type mismatch error when I rewrite the Example project in the same way.

I could not remove `connEscapeName` from `TestImport` in Example.
I couldn't find any trace of a commit where `connEscapeName` was removed from persistent.
I have no clue how to rewrite it.

## Policy concerns

I have set up a policy to create a new type alias and specify a new HaskellName, but I have no idea how to change the policy.
It might be better to expand Template Haskell to some extent and rewrite the arguments.

### CODE REVIEW

**Comment by ncaq** [comment]
working log(Japanese).
[serversessionのアップデートで新しいpersistentに対応した時の格闘記録 - ncaq](https://www.ncaq.net/2022/05/02/22/08/12/)

**Comment by snoyberg** [comment]
No one is really maintaining this right now. Would you be interested in taking it over?

**Comment by ncaq** [comment]
@snoyberg 
We need this project for our product.
So if there is no maintainer, I will have to maintain it.
I have no experience in maintaining FLOSS for other authors, so I don't know if I can do it well.
But I have no choice but to do it, so I will take on the task.
I would like to be a maintainer.

---

On a different note, do you know who to ask about TestImport not working because connEscapeName has been removed from persistent?
Should I ask the persintent maintainer?
I'm still not sure what would be appropriate to rewrite Yesod's newly created sample project, even if I were to fix the fact that it is still lts-16.

**Comment by snoyberg** [comment]
> I would like to be a maintainer.

Awesome! I've invited you to this repo. I can add you on Hackage as well if you tell me your Hackage username and the packages you need to be able to maintain.

> Should I ask the persintent maintainer?

Yes, that probably makes the most sense, I'm not familiar with the changes.

**Comment by ncaq** [comment]
> Awesome! I've invited you to this repo. I can add you on Hackage as well if you tell me your Hackage username and the packages you need to be able to maintain.

My Hackage username is `ncaq`  and email `ncaq@ncaq.net` .

I didn't quite understand what you meant by " needed packages," but it looks like the only thing I'll be tinkering with directly, rather than in PR form, will be around serversession for a while.

**Comment by snoyberg** [comment]
Cool, I've added you as a Hackage maintiner for serversession: https://hackage.haskell.org/package/serversession/maintainers/.

**Comment by ncaq** [comment]
It seems to have stopped working because CompositeRef stopped doing its job.
[Constructor `CompositeRef` for `ReferenceDef` is no longer used · Issue #1285 · yesodweb/persistent](https:
//github.com/yesodweb/persistent/issues/1285)

**Comment by ncaq** [comment]
It seems that data without PRIMARY is difficult to handle with the new Persistent.
I guess the best I can do is to specify key as Primary and allow automatic migration.

**Comment by ncaq** [comment]
I think we have done most of it.
On my next working day, I will check the development version of our product to make sure there are no problems with functionality, and if there are no problems, I will merge it and release it.

**Comment by ncaq** [comment]
After a little research, it seems to be working properly, so I will merge and release it.

**Pull request merged**
